---
stack_name: {{ 'routes-' + var.environment }}
template_path: workload/routes.yaml


parameters:
  Environment: '{{ var.environment }}'

dependencies:
  - 'dev/subnets.yaml'
  - 'dev/security-groups.yaml'