---
version: 0.2

env:
  secrets-manager:
    db_password: /Servian-Tech-Challenge/database/master:password
    db_host: /Servian-Tech-Challenge/database/master:host
  exported-variables:
    - AMI_ID

phases:
  install:
    commands:
      - echo "Installing HashiCorp Packer ..."
      - cd AWS/buildspecs/
      - chmod 755 scripts/*
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.5.4/packer_1.5.4_linux_amd64.zip && unzip packer.zip
  build:
    commands:
       - |
          if [ "${BRANCH}" == "master" ]; then
            echo "Pulling tested AMI_ID from ParameterStore."
            AMI_ID=$(aws ssm get-parameter --name "${APP_NAME}-TESTED-AMI" --query "Parameter.Value" --output text)
          elif [ "${IS_BUILD_REQUIRED}" == "true" ]; then
            ./scripts/ami-builder.sh --application "${APP_NAME}"
            source ./ami_id
          else
            echo "Building AMI is not required for application ${APP_NAME} as mentioned in source(app-config.env)"    
          fi