---
stack_name: {{ 'challengeApp-' + var.environment }}
template_path: workload/app.yaml

parameters:
  Env: '{{ var.environment }}'
  VpcCidr: '{{ var.vpc_cidr }}'
  AmiId: '{{ var.ami_id }}'
  DbName: '{{ var.db_name }}'
  DbPassword: '{{ var.db_password }}'
  DbHost: '{{ var.db_host }}'
  NodeType: 'Multiple'

dependencies:
  - 'prod/load-balancer.yaml'
  - 'prod/db.yaml'