---
stack_name: {{ 'db-' + var.environment }}
template_path: workload/rds.yaml

parameters:
  Environment: '{{ var.environment }}'
  DbAllocatedStorage: "30"
  DbMultiAZ: "true"

dependencies:
  - 'prod/routes.yaml'