---
stack_name: {{ 'routes-' + var.environment }}
template_path: workload/routes.yaml

parameters:
  Environment: '{{ var.environment }}'

dependencies:
  - 'prod/subnets.yaml'
  - 'prod/security-groups.yaml'