---
stack_name: {{ 'subnets-' + var.environment }}
template_path: workload/workload_subnets.yaml

parameters:
  VpcCidr: '{{ var.vpc_cidr }}'
  Environment: '{{ var.environment }}'

dependencies:
  - 'prod/vpc.yaml'